### ISSUE TITLE
A update of the homepage

### ISSUE THREAD

**Issue by NanaVan** [SchottkySpectroscopyIMP/schottkyspectroscopyimp.github.io#1]
@nerdull have a look at it~
There something I need to update,
1. a nice spectrum of the ions as the homepage title picture
2. a nice post for claiming the set-up of our homepage
3. the contain of our project
What I was added,
1. "about" page,
2. project list script

**Comment by nerdull** [comment]
Good to see the new site being deployed!
I'll take care of point 1, tell me please the preferable size for such a figure.

@NanaVan

**Comment by NanaVan** [comment]
The basic of our homepage has been established. Have a look at it ~
An other question, shall we ask other Schottky guys in GSI or RIKEN to share their group site's link with us?
We can add the <b>Links</b> on our `About` page.
@nerdull

**Comment by nerdull** [comment]
@NanaVan Yeah, I like your idea, please go ahead!
